# Generated by Django 3.2.9 on 2021-11-28 02:13

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='article_img/')),
                ('slug', models.CharField(max_length=300, unique=True)),
                ('snippet', models.CharField(max_length=500)),
                ('detail', ckeditor.fields.RichTextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('is_interesting', models.BooleanField(default=False)),
                ('is_mysterious', models.BooleanField(default=False)),
                ('most_read', models.BooleanField(default=False)),
                ('most_shared', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
