# Generated by Django 3.2.9 on 2021-11-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211128_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='alternative_text',
            field=models.CharField(default='ffff', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='image_caption',
            field=models.CharField(default='credit', max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=255),
        ),
    ]
