# Generated by Django 3.2.9 on 2021-11-29 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211128_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='alternative_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_caption',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.article')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
